### ISSUE TITLE
Can eqWAlizer distinguish between different numeric types?

### ISSUE THREAD

**Issue by kikofernandez** [WhatsApp/eqwalizer#11]
Hi! I know that currently (v 0.12.12) eqWAlizer cannot distinguish between different numeric types ([doc here](https://github.com/WhatsApp/eqwalizer/blob/main/docs/reference/types.md#numeric-types)). I was wondering if there is a technical issue with it per se or if this is something that could be worked out in the future, to catch more typing errors.

Thanks!

**Comment by ilya-klyuchnikov** [comment]
Sorry for the very late reply.

We decided not to support different numeric types for a combination of reasons:

1. Simplicity of the internals of the type-checker. We did experiments with supporting the Numeric tower (https://www.ccs.neu.edu/home/stamourv/papers/numeric-tower.pdf) and while it's possible - it complicates the internals a lot.
2. Our experiments showed that type-checking with Numeric tower would be noisy. 
3. It has never been escalated by our primary users and something that is critical or important.
4. In general, - having different numeric types (and even ranges) seems to us as an unnecessary over-complication. 
5. Except Typed Racket (with strong typing discipline) - no other popular language has Numeric Tower in a sense of having types like positive integers, negative integers, ...

**Comment by ilya-klyuchnikov** [comment]
@kikofernandez 

A few additional points:

- There is an asymmetry in current types: there are `pos_integer()`, `neg_integer()` but no `pos_float()`, `neg_float()`, etc

So, it becomes hairy to type-check the following code:

```
-spec convert(pos_integer()) -> pos_integer().
convert(Min) -> round(Min / 60).
```
