### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by tothlac** [WhatsApp/eqwalizer#13]
We would like to use eqwalizer on many of our repositories. We have about 200 of them.

I have some questions:
- how can I debug? I would like to compile eqwalizer so then I would able to print what it is doing inside, but I could not figure out how to compile to get an elp binary. Is there documentation about that? 
- We still use older otp versions: otp 23 and 24 are supported. When I try to run `elp eqwalize-all` with these older versions I got:
```
thread 'thread 'thread 'thread '<unnamed><unnamed><unnamed><unnamed>' panicked at '' panicked at '' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: RecvErrorcalled `Result::unwrap()` on an `Err` value: "SendError(..)"called `Result::unwrap()` on an `Err` value: "SendError(..)"called `Result::unwrap()` on an `Err` value: "SendError(..)"', crates/parse_server/src/lib.rs', :', thread 'thread 'crates/parse_server/src/lib.rs', crates/parse_server/src/lib.rs<unnamed>:thread '' panicked at '188187called `Result::unwrap()` on an `Err` value: "SendError(..)"::crates/parse_server/src/lib.rs', 35:
<unnamed>187note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
crates/parse_server/src/lib.rs' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"<unnamed>', 40' panicked at 'thread 'crates/parse_server/src/lib.rs
called `Result::unwrap()` on an `Err` value: "SendError(..)"<unnamed>:', ' panicked at '35crates/parse_server/src/lib.rscalled `Result::unwrap()` on an `Err` value: "SendError(..)"
:', 187crates/parse_server/src/lib.rs::35:187
```
Is it planned to make it compatible with at least the above-mentioned erlang versions?

- We would definitely like to use it in our newer elixir projects. In README.md it is mentioned PRs would be appreciated on this field. Can you give some guidance on what should be implemented to make it work with elixir projects?

**Comment by ilya-klyuchnikov** [comment]
It turns out that eqWAlizer works with on top of OTP 23 and 24 - we would need to provide corresponding builds in downloads. Please expect them next week.

> how can I debug? I would like to compile eqwalizer so then I would able to print what it is doing inside, but I could not figure out how to compile to get an elp binary. 

You can look into GH CI steps to repro builds locally:
- https://github.com/WhatsApp/eqwalizer/blob/main/.github/workflows/ci.yml
- https://github.com/WhatsApp/eqwalizer/blob/main/.github/workflows/release.yml

**Comment by tothlac** [comment]
Thanks for the quick answer. I will try to locally compile it from source.
What about elixir support? Do you plan to add support for elixir? If not what should be done?
One more question: when I run `elp equalize-all` it compiles all the dependencies. On our jenkins servers when it reaches that phase everything has been compiled by that time, so compiling is not necessary. Would it possible to add a `--compile=false` option with a default value of true?

**Comment by sopotc** [comment]
Wrt to elixir it is elaborated a bit (not much) more in [this](https://www.beamrad.io/35) podcast at 29:30.

**Comment by ilya-klyuchnikov** [comment]
The latest release has now `elp-linux-otp-23.tar.gz` artefact which is runnable on Linux with OTP 23. (And is also runnable with OTP 24 and 25).

https://github.com/WhatsApp/eqwalizer/releases/tag/v0.13.18

**Comment by tothlac** [comment]
I've tried it, and it works on linux quite well. Unfortunately I've macos. Do you plan to release it for that osx as well?

**Comment by ilya-klyuchnikov** [comment]
> Do you plan to release it for that osx as well?

yes, - we can do this

**Comment by tothlac** [comment]
Thanks, that would be good.

**Comment by ilya-klyuchnikov** [comment]
We now provide OTP-23 compatible builds for both linux and mac. See https://github.com/WhatsApp/eqwalizer/releases/tag/v0.15.13

**Comment by ilya-klyuchnikov** [comment]
closing, OTP-23 compatible builds are provided now
