### ISSUE TITLE
Elp fails to run on RHEL 8 OS

### ISSUE THREAD

**Issue by benjoe87** [WhatsApp/eqwalizer#18]
When I try to run elp on a RHEL 8  it fails with following error message:

```
[vagrant@rhel8 ~]$ ./elp 
./elp: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by ./elp)
```

This is because Ubuntu 20.04 has newer glibc then RHEL8 and Glibc not forward compatible.

One possible solution is to link against musl instead of glibc:
https://doc.bccnsoft.com/docs/rust-1.36.0-docs-html/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html

**Comment by benjoe87** [comment]
I have opened a PR to solve this issue:
https://github.com/WhatsApp/eqwalizer/pull/19

**Comment by VLanvin** [comment]
The latest release (v0.14.2) features #19 , so closing the issue.
