### ISSUE TITLE
Wrong version output by elp

### ISSUE THREAD

**Issue by tsloughter** [WhatsApp/eqwalizer#27]
I download 0.15.3 linux build, https://github.com/WhatsApp/eqwalizer/releases/download/v0.15.13/elp-linux.tar.gz, and run `version`:

```
$ elp version
elp 0.13.18
```

**Comment by ilya-klyuchnikov** [comment]
yes,  - we forgot to manually bump the version before the GH release last two times. It would be fixed in the next release.
