### ISSUE TITLE
Cannot eqwalize a single file/module: rebar3 command build_info not found

### ISSUE THREAD

**Issue by erszcz** [WhatsApp/eqwalizer#32]
I'm trying to run some comparisons between Gradualizer / Etylizer / Eqwalizer, but with the last one I'm getting the following error:

```
$ uname -a
Darwin x7.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64
$ /Users/erszcz/work/erszcz/erlang-type-checker-comparison/elp version
elp 0.17.16
$ /Users/erszcz/work/erszcz/erlang-type-checker-comparison/elp eqwalize test/known_problems/should_fail/binary_comprehension.erl
  Loaded rebar3 build_info
Failed to read rebar build info for config file /Users/erszcz/work/erszcz/gradualizer/./rebar.config, rebar 3.22.0+build.5279.ref1b6297dd on Erlang/OTP 25 Erts 13.2.2: cd "/Users/erszcz/work/erszcz/gradualizer" && "rebar3" "as" "test" "build_info" "--to" "/var/folders/vq/5gp3vyx57fn1tz6x3_xbp1ww0000gp/T/.tmpokB2i0" failed, exit status: 1
stdout:===> Command build_info not found
```

Rebar3 3.22.0 is the latest release and https://rebar3.org/docs/commands/ doesn't mention a `build_info` command, so I'm not sure what's going on. Is there something I could try to run eqwalizer on a single file?

**Comment by ilya-klyuchnikov** [comment]
Have you followed the steps in https://github.com/WhatsApp/eqwalizer#using-it-with-rebar3-projects?

Pay attention to the step 3 about adding dependencies (a library and a plugin).

**Comment by erszcz** [comment]
Ahhh, right, that's it! Thanks for the pointer and sorry for the confusion.
