### ISSUE TITLE
Doc improvements for non-rebar builds?

### ISSUE THREAD

**Issue by Olivier-Boudeville** [WhatsApp/eqwalizer#44]
Hi,

Thanks for this interesting tool!

When reading https://github.com/WhatsApp/eqwalizer#using-it-with-non-rebar-projects (with Erlang 26.1) I have been a bit confused by:
*  "_Ensure eqwalizer_support is added as a dependency, and that its ebin folder is reachable and populated with .beam files_." as the prior action was to download only the elp binary, which is an executable (no ebin directory, no BEAM files); is it a leftover from the rebar section?
* the https://github.com/WhatsApp/eqwalizer/blob/main/mini-elp/test_projects/standard/build_info.json example lists 'eqwalizer' (and not 'eqwalizer_support', as mentioned in the doc) among the applications, which is a bit surprising (can we run Eqwalizer without eqwalizer? Would such dependency be optional? If not, maybe it would be better if it was automatically added/implied? Is it 'eqwalizer' or 'eqwalizer_support'? ). Apparently there is another reference to this ebin directory, so what is the point of the binary install of only the 'elp' executable? 

At least if no relevant eqwalizer dependency is listed in the conf file, no error is found afterwards, whereas a ebin full of BEAM files with certainly many type errors was specified: 

```
~/Software/eqwalizer/bin/elp eqwalize-all --project ./conf/xxx-for-eqwalizer.json
Loading JSON manifest  
                                                                                                                                               
Loading applications      ████████████████████ 1/1                                                                                                                   Seeding database                                                                                                                                                     
Compiling dependencies                                                                                                                                               
eqWAlizing                ████████████████████ 0/0                                                                                                                  NO ERRORS
```

(if it is due to no proper eqwalizer or eqwalizer_support being specified in the conf file, then maybe a check could be made and an error be raised?)

For more information, here is the very basic conf/xxx-for-eqwalizer.json file (a version of it without eqwalizer-related app/dep; slightly edited):

```
{

	"apps": [

		{   "name": "xxxx",

			"__comment": "Relative to project root:",
			"dir": ".",

			"__comment": "Not wanting the tool to operate on sources, but on BEAMs: (relative to app dir)",
			"src_dirs": [ "src" ],

			"__comment": "(relative to app dir)",
			"extra_src_dirs": [],

			"__comment": "A single path, not a list thereof  (relative to app dir)",
			"ebin": "ebin",

			"__comment": "Symlinks to all .hrl there: (relative to app dir)",
			"include_dirs": [ "include" ],

			"macros": []
		}

	],

	"root": "."
}

```

On a side note, maybe I missed it in  the doc, but it would be interesting to state whether eqwalizer relies on the BEAMs and/or on the source files to operate; I expected the BEAMs (which is fine, notably if user code uses very custom-built, possibly with parse transforms), as the app's ``ebin`` directory has to be specified, but on the other hand ``src_dirs`` may/must be specified as well.

**Comment by VLanvin** [comment]
You're right, the part about having eqwalizer_support `ebin` dir populated with BEAM files is a leftover from the rebar section.

To clarify several points here:
- eqWAlizer only type-checks source files. It uses source files to load modules specified in the `apps` part of the `build_info.json`, and type-checks them. BEAM files are used for dependencies: eqWAlizer loads type and line/col information from them, but does not type-check them. Hence the absence of type-errors here.
- Following the previous point, BEAM files are not needed for modules/apps specified in the `apps` part of the JSON file, including `eqwalizer_support`.
- `eqwalizer_support` has, for some reason, been renamed into just `eqwalizer` for mini-elp's tests. I agree it's confusing. `eqwalizer_support` can be obtained [here](https://github.com/WhatsApp/eqwalizer/tree/main/eqwalizer_support), and is needed as it contains the definition of some types used internally by eqWAlizer.

I'll clarify/add this info to the docs. Thanks for the feedback!

**Comment by Olivier-Boudeville** [comment]
Thanks for your answer! Even if due to parse-transforms I am more fond of tools operating on BEAM files, I will surely give Eqwalizer a try in the future. I close this issue, thanks again for your feedback!
