### ISSUE TITLE
`elp version` reports previous version

### ISSUE THREAD

**Issue by eKristensen** [WhatsApp/eqwalizer#47]
When I build from source downloaded yesterday or download the latest version the `elp version` command report version 0.17.16 which is the previous version. I would expect it to say it is version 0.20.31. Is this intentional?

**Comment by ilya-klyuchnikov** [comment]
yep. - we forgot to update the version in `Cargo.toml` before releasing 0.20.31

**Comment by ilya-klyuchnikov** [comment]
fixed for the last release 0.23.6
