### ISSUE TITLE
Could not eqwalize: receiving message

### ISSUE THREAD

**Issue by gilbertwong96** [WhatsApp/eqwalizer#50]
## Description

After I type the command `elp eqwalize-all`, the result is a little weird:

``` shell
$ elp eqwalize-all
  Loading build info
  Loading applications      ████████████████████
  Seeding database
  Compiling dependencies
  Gathering modules         ████████████████████ 128/128
  Parsing modules           ████████████████████ 5/5
  EqWAlizing                ████████████████████ 5/5
Could not eqwalize: receiving message
```

## Tools version

The elp I used is built with the eqwalizer on my MacBook (Apple M1 Pro).

The elp version:

``` shell
$ git describe --tags
2023-12-15
```

The eqwalizer version:

``` shell
$ git describe --tags
v0.23.6
```

The java version:

```shell
$ java version
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22)
OpenJDK 64-Bit Server VM GraalVM CE 17.0.9+9.1 (build 17.0.9+9-jvmci-23.0-b22, mixed mode, sharing)
```

The sbt version:

```shell
$ sbt --version
sbt version in this project: 1.9.8
sbt script version: 1.9.8
```

The rust version:

```shell
$ rustc --version
rustc 1.75.0 (82e1608df 2023-12-21)
```

The OTP Version: `25.3.2.7`

```shell
asdf list erlang
  25.0.1
  25.3.2.2
 *25.3.2.7
  26.1.1
```

## OS

The operating system I use is `macOS Sonoma Version 14.2.1`.

**Comment by VLanvin** [comment]
This looks like a recent bug we had due to increased parallelism.

I've launched the compilation of a new release, v0.25.3, which should hopefully fix it.

**Comment by gilbertwong96** [comment]
I have upgraded the eqwalizer to v0.25.3. However, the equalizer is not functioning as expected. It still prompts the error: `Could not eqwalize: receiving message`.

**Comment by gilbertwong96** [comment]
After I upgrade the elp version to the latest main branch https://github.com/WhatsApp/erlang-language-platform/commit/926c661b5f11dc377dd5cfc7c6a6f51b4c2aafb5, it works.


Please launch a new release for the https://github.com/WhatsApp/erlang-language-platform.
