### ISSUE TITLE
Wrong warning: Unused record field ([missing name].queue)

### ISSUE THREAD

**Issue by Zabrane** [WhatsApp/eqwalizer#63]
Hi guys

This works with no warning:
```erlang
-define(FOO, foo).
-record(?FOO, {
    queue :: term()
}).
```

whereas `eqwalizer` warns about the following valid code:
```erlang
-record(?MODULE, {
    queue :: term()
}).
```
`Unused record field ([missing name].queue)`

Of course, the `queue` field is set in the function `open_queue/1`.

My config:
```bash
$ sw_vers | head -2
ProductName:            macOS
ProductVersion:         14.6.1

$ erl
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [lock-counting]
Eshell V15.0.1 (press Ctrl+G to abort, type help(). for help)

$ elp version
elp 1.1.0+build-2024-04-17

%% VSCode
$ code --version
1.92.2
fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
x64
```

Help appreciated
Z.

**Comment by Zabrane** [comment]
> 1. `elp eqwalize` runs erl_lint (part of erlc compiler) before type-checking. This warning is produced by erl_lint and not by eqwalizer in the first place.

Oh didn't know about the linter before.

>     2. Can you provide a reproducible example?

Sure thing. Here you are:
```erlang
-module(foo).
-export([ test/0 ]).
-record(?MODULE, {
    queue      :: term()
}).
test() ->
    #?MODULE{queue = ok}.
```
![Screenshot_2024-08-30_at_12_49_54](https://github.com/user-attachments/assets/29482f9f-155c-49da-8f12-797c9b8c49de)

**Comment by ilya-klyuchnikov** [comment]
ok, - it's a warning generated by ELP, not by eqwalizer.
Though I see that it's a bug.

Can you open a corresponding task in https://github.com/WhatsApp/erlang-language-platform ?

Thanks

**Comment by Zabrane** [comment]
@ilya-klyuchnikov DONE. Many thanks for your support.
https://github.com/WhatsApp/erlang-language-platform/issues/51
