### ISSUE TITLE
Incompatible type issue headache

### ISSUE THREAD

**Issue by Zabrane** [WhatsApp/eqwalizer#64]
Hi guys

I'm facing types incompatibility on a very simple example which I couldn't solve.
Here is my code:
```erlang
-spec table_name() -> atom().
table_name() ->
    {ok, V} = application:get_env(?MODULE, table_name),
    V.
```
`eqwalizer` complains about `term()` non compatible with `atom()`:
```text
`V`.
Expression has type:   term()
Context expected type: atom()
        See https://fb.me/eqwalizer_errors#incompatible_types
```

I've changed my code forcing it to always return an `atom()`, or to fail:
```erlang
-spec table_name() -> atom() | no_return().
table_name() ->
    {ok, V} = application:get_env(?MODULE,table_name),
    true == is_atom(V),
    V.
```

 but `eqwalizer` still complains:
```text
`V`.
Expression has type:   term()
Context expected type: atom() | none()
  term() is not compatible with atom() | none()
  because
  term() is not compatible with atom()
        See https://fb.me/eqwalizer_errors#incompatible_types
```

How am i supposed to solve this?
Help appreciated. Thanks.

```bash
$ elp version
elp 1.1.0+local

$ erl
Eshell V15.0.1 (press Ctrl+G to abort, type help(). for help)

$ sw_vers | head -2
ProductName:		macOS
ProductVersion:		14.6.1
```

**Comment by Zabrane** [comment]
My bad, this solves it.
```erlang
-spec table_name() -> atom() | no_return().
table_name() ->
    {ok, V} = application:get_env(?MODULE,table_name),
    true = is_atom(V),
    V.
```

Is there a better solution?

**Comment by Zabrane** [comment]
Hey @michalmuskala  @ilya-klyuchnikov 

Let's take another example which i don't know how to fix by changing the typespec of the same function:
```erlang
-spec table_name() -> file:filename_all().
table_name() ->
    {ok, V} = application:get_env(?MODULE,table_name),
    true = is_list(V),
    filename:join("/tmp", V).
```

The error says:
```text
`V`.
Expression has type:   [term()]
Context expected type: file:name_all()

  [term()] is not compatible with file:name_all()
  because
  [term()] is not compatible with string() | atom() | file:deep_list() | binary()
  because
  [term()] is not compatible with string()
        See https://fb.me/eqwalizer_errors#incompatible_types
```
It seems impossible to solve with my limited knowledge of `eqwalizer`.

**Comment by VLanvin** [comment]
Have you added the `eqwalizer_support` app to your project? It should be overriding the spec of `application:get_env/2` to return `{ok, dynamic()}` instead of `{ok, term()}`, which would solve the issue.

Otherwise it's practically impossible to refine type `term()` to complex types such as `file:name_all()`. The solution would be to simply ignore the error:
```erlang
-spec table_name() -> file:filename_all().
table_name() ->
    {ok, V} = application:get_env(?MODULE,table_name),
    % eqwalizer:ignore
    filename:join("/tmp", V).
```

**Comment by Zabrane** [comment]
> Have you added the `eqwalizer_support` app to your project? It should be overriding the spec of `application:get_env/2` to return `{ok, dynamic()}` instead of `{ok, term()}`, which would solve the issue.

@ilya-klyuchnikov  how can i enable `eqwalizer_support`?
Could you please show me? Thanks.
